# Generated by Django 5.0.6 on 2025-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images'),
        ),
        migrations.DeleteModel(
            name='WeeklyFoodLog',
        ),
    ]
