# Generated by Django 5.0.6 on 2025-02-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplanner', '0002_alter_food_image_delete_weeklyfoodlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedFood',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dietplanner.food')),
                ('cooked_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingFood',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dietplanner.food')),
                ('ready_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
