# Generated by Django 5.0.6 on 2025-02-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplanner', '0003_completedfood_pendingfood_alter_food_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingfood',
            name='ready_time',
            field=models.TimeField(),
        ),
    ]
