# Generated by Django 5.0.6 on 2025-02-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietplanner', '0004_alter_pendingfood_ready_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingfood',
            name='cooked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CompletedFood',
        ),
    ]
