# Generated by Django 5.0.6 on 2025-02-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietplanner', '0002_auto_minimum_quantity'),
        ('dietplanner', '0007_ingredient_quantity_ingredient_unit_inventory'),
    ]

    operations = [
    ]
